const tours = [
    // ITALIJA
    {
        _id: '1',
        name: 'Obilazak Rima',
        country: 'Italija',
        location: 'Rim, Italija',
        image: 'https://media.danubeogradu.rs/2015/06/rim-1.jpg',
        description: 'Upoznajte Rim kroz organizovan obilazak ključnih znamenitosti: Koloseum, Forum Romanum, Panteon i Vatikan sa Bazilikom Svetog Petra. Program obuhvata vođene ture uz stručne vodiče, slobodno vreme za šetnju i uživanje u lokalnoj kuhinji. Osetite jedinstvenu atmosferu grada koji spaja istoriju, umetnost i svakodnevni život. Ulaznice uključene u cenu.',
        duration: 1,
        category: 'Kultura',
        price: 6000,
        maxGroupSize: 20,
        available: true,
        rating: 4.5,
        numReviews: 26,
    },
    {
        _id: '2',
        name: 'Obilazak katedrale Duomo',
        country: 'Italija',
        location: 'Milano, Italija',
        image: 'https://duomodimilanotickets.com/wp-content/uploads/2025/01/Duomo-di-Milano-at-Night.webp',
        description: 'Poseta čuvenoj milanskoj katedrali Duomo, jednom od najvećih i najlepših gotičkih hramova u Evropi. Program uključuje obilazak unutrašnjosti katedrale, uspon na terase sa panoramskim pogledom na grad, kao i slobodno vreme za šetnju po trgu Piazza del Duomo i okolnim ulicama. Obilazak pruža jedinstvenu priliku da se upoznate sa kulturnim i arhitektonskim simbolom Milana. Ulaznice uključene u cenu.',
        duration: 1,
        category: 'Kultura',
        price: 4000,
        maxGroupSize: 10,
        available: true,
        rating: 4,
        numReviews: 15,
    },
    {
        _id: '3',
        name: 'Jezero Como',
        country: 'Italija',
        location: 'Como, Italija',
        image: 'https://fibula.co.rs/Slike/Milano-Jezero-Komo/1.jpg',
        description: 'Uživajte u organizovanom obilasku jednog od najlepših jezera u Italiji. Program obuhvata vožnju brodom, posetu gradovima Komo i Bellagio, kao i slobodno vreme za šetnju i odmor uz obalu. Izlet je osmišljen da spoji prirodne lepote, kulturne znamenitosti i prijatnu atmosferu, uz vođene ture i mogućnost individualnog doživljaja.',
        duration: 1,
        category: 'Priroda',
        price: 7000,
        maxGroupSize: 20,
        available: true,
        rating: 5,
        numReviews: 25,
    },
    {
        _id: '4',
        name: 'Izlet u Veneciju',
        country: 'Italija',
        location: 'Venecija, Italija',
        image: 'https://www.lastminuteponude.com/resursi/images/00002233196530fd604cc12/Venecija%20%283%29.webp',
        description: 'Prvi dan obuhvata obilazak glavnih znamenitosti: Trg Svetog Marka, Bazilika Svetog Marka, Duždeva palata i vožnja gondolom kroz kanale. Nakon vođene ture, predviđeno je slobodno vreme za šetnju i uživanje u venecijanskoj atmosferi. Drugog dana program uključuje posetu ostrvima Murano i Burano, poznatim po staklarstvu i šarenim kućama, uz mogućnost degustacije lokalnih specijaliteta. Izlet je osmišljen da spoji kulturno-istorijske sadržaje i jedinstven doživljaj lagune. Ulaznice i prevoz uključeni u cenu.',
        duration: 2,
        category: 'Kultura',
        price: 12000,
        maxGroupSize: 25,
        available: true,
        rating: 4.5,
        numReviews: 30,
    },

    // ŠPANIJA
    {
        _id: '5',
        name: 'Obilazak Barcelone',
        country: 'Španija',
        location: 'Barcelona, Španija',
        image: 'https://www.felixtravel.rs/img.php?i=evropski-gradovi/barselona/spanija-barselona-felix-travel-2.jpg&w=500&h=375',
        description: 'Obilazak obuhvata prvo razgledanje centra grada: Trg Katalonije, La Rambla i Gotčka četvrt, uz posetu čuvenoj Sagradi Familii. Posle toga program uključuje obilazak dela grada posvećenog Antoniu Gaudiju – Park Güell i Casa Batlló, kao i slobodno vreme za šetnju i kupovinu. Ulaznice uključene u cenu.',
        duration: 1,
        category: 'Kultura',
        price: 8000,
        maxGroupSize: 20,
        available: true,
        rating: 5,
        numReviews: 38,
    },
    {
        _id: '6',
        name: 'Upoznajte Madrid',
        country: 'Španija',
        location: 'Madrid, Španija',
        image: 'https://images.contentstack.io/v3/assets/blt06f605a34f1194ff/bltdb42d0af0dddb0dd/65006732539fa162b64ae755/0_-_BCC-2023-MADRID-LANDMARKS-0.webp?fit=crop&disable=upscale&auto=webp&quality=60&crop=smart',
        description: 'Prvo obilazimo glavne znamenitosti: Puerta del Sol, Plaza Mayor, Kraljevska palata i katedrala Almudena. Posle toga program uključuje posetu muzeju Prado i parku Retiro, kao i slobodno vreme za uživanje u lokalnoj gastronomiji i atmosferi grada. Izlet je osmišljen da spoji kulturno-istorijske sadržaje, umetnost i svakodnevni život španske prestonice. Ulaznice uključene u cenu.',
        duration: 1,
        category: 'Kultura',
        price: 7500,
        maxGroupSize: 20,
        available: true,
        rating: 4.5,
        numReviews: 45,
    },
    {
        _id: '7',
        name: 'Palata Alhambra ',
        country: 'Španija',
        location: 'Granada, Španija',
        image: 'https://www.barcelo.com/guia-turismo/wp-content/uploads/granada.jpg',
        description: 'Organizovan obilazak Alhambre, jedne od najpoznatijih maurskih palata i utvrđenja u Evropi. Program obuhvata posetu Nasrid palatama, Generalife vrtovima i Alcazabi, uz stručno vođenje koje približava istoriju i umetnost ovog jedinstvenog kompleksa. Nakon obilaska, predviđeno je slobodno vreme za šetnju starim delom Granade i uživanje u lokalnoj gastronomiji. Izlet je osmišljen da spoji kulturno-istorijsko nasleđe i autentičnu atmosferu Andaluzije.',
        duration: 1,
        category: 'Istorija',
        price: 5000,
        maxGroupSize: 30,
        available: true,
        rating: 4,
        numReviews: 18,
    },
    {
        _id: '8',
        name: 'Obilazak Sevilje',
        country: 'Španija',
        location: 'Sevilja, Španija',
        image: 'https://mcdn.pro/data/objects/images/63156/sevilja1-uwipvt-l-irke0i.jpg',
        description: 'Obilazak započinjemo Katedralom u Sevilji sa čuvenom Giraldom, Real Alcázar i šetnjom kroz istorijsku četvrt Santa Cruz. Nakon vođene ture, predviđeno je slobodno vreme za uživanje u lokalnoj atmosferi i gastronomiji. Nakon toga program uključuje posetu Plazi de España i parku María Luisa, kao i obilazak Metropol Parasol – moderne arhitektonske atrakcije sa panoramskim pogledom na grad. Izlet je osmišljen da spoji bogato kulturno-istorijsko nasleđe i savremeni duh Sevilje. Ulaznice uključene u cenu.',
        duration: 1,
        category: 'Kultura',
        price: 7000,
        maxGroupSize: 20,
        available: true,
        rating: 4.5,
        numReviews: 40,
    },

    // FRANCUSKA
    {
        _id: '9',
        name: 'Upoznajte Pariz',
        country: 'Francuska',
        location: 'Pariz, Francuska',
        image: 'https://gotripzi.com/_astro/paris-fr-hero.BfTcStng.webp',
        description: 'Obilazak započinjemo Ajfelovim tornjem, Trijumfalnom kapijom i šetnjom Jelisejskim poljima, uz mogućnost krstarenja Senom. Zatim idemo u posetu Luvru, Tiljerijskom parku i Latinskoj četvrti, sa slobodnim vremenom za individualne aktivnosti. Ulaznice uključene u cenu.',
        duration: 1,
        category: 'Kultura',
        price: 10000,
        maxGroupSize: 20,
        available: true,
        rating: 5,
        numReviews: 35,
    },
    {
        _id: '10',
        name: 'Dvorac Versaj',
        country: 'Francuska',
        location: 'Versaj, Francuska',
        image: 'https://xdn.tf.rs/2021/02/06/galerija-ogledala-versajski-dvorac.jpg',
        description: 'Organizovan obilazak čuvene palate Versaj, jednog od najznačajnijih spomenika francuske istorije i umetnosti. Program obuhvata posetu raskošnim dvoranama, uključujući Dvoranu ogledala, kao i šetnju kroz prostrane vrtove i fontane. Nakon vođenog obilaska, predviđeno je slobodno vreme za individualne aktivnosti i uživanje u ambijentu. Izlet je osmišljen da spoji kulturno-istorijsko nasleđe i jedinstvenu atmosferu francuskog dvorskog života. Ulaznice uključene u cenu.',
        duration: 1,
        category: 'Istorija',
        price: 5000,
        maxGroupSize: 30,
        available: true,
        rating: 4,
        numReviews: 15,
    },
    {
        _id: '11',
        name: 'Azurna obala — Nica i Kan',
        country: 'Francuska',
        location: 'Nica, Francuska',
        image: 'https://www.travelmagazine.rs/wp-content/uploads/2020/06/france-nice-city-view.jpg',
        description: 'Prvi dan započinjemo obilaskom Nice, šetnjom Promenade des Anglais i starim gradom sa mediteranskom atmosferom i živopisnim pijacama. Nakon toga je predviđeno slobodno vreme za individualne aktivnosti. Povratak ka hotelima u večernjim časovima. Drugog dana sledi vožnja do Kana, poznatog po filmskom festivalu i luksuznoj rivijeri. Predviđen je obilazak šetališta Croisette, starog grada Le Suquet i slobodno vreme za uživanje u kafićima ili šoping. Izlet je osmišljen da spoji šarm Azurne obale i glamur svetski poznatog Kana. Ulaznice i prevoz uključeni u cenu.',
        duration: 2,
        category: 'Kultura',
        price: 9000,
        maxGroupSize: 15,
        available: true,
        rating: 4.5,
        numReviews: 30,
    },
    {
        _id: '12',
        name: 'Provansa — lavanda i vino',
        country: 'Francuska',
        location: 'Provansa, Francuska',
        image: 'https://belvi.rs/wp-content/uploads/2023/07/provansa.jpg',
        description: 'Organizovan obilazak jednog od najlepših regiona Francuske, poznatog po lavandinim poljima, vinogradima i slikovitim selima. Program obuhvata posetu Avinjonu sa čuvenom Papinskom palatom, šetnju kroz tipična provansalska sela poput Gordesa i Roussillona, kao i uživanje u pejzažima lavande i vinogradima. Predviđeno je i slobodno vreme za degustaciju lokalnih vina i specijaliteta. Izlet je osmišljen da spoji kulturno-istorijsko nasleđe, prirodne lepote i autentičnu atmosferu Provanse.',
        duration: 1,
        category: 'Priroda',
        price: 7000,
        maxGroupSize: 12,
        available: true,
        rating: 4.5,
        numReviews: 20,
    },

    // GRČKA
    {
        _id: '13',
        name: 'Atina — Partenon',
        country: 'Grčka',
        location: 'Atina, Grčka',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPfCjWR2xlxBqTPJdDQl4K2sohgS7KN-vpfQ&s',
        description: 'Dan započinjemo obilaskom Akropolja sa Partenonom, Propilejima i Erehtejon hramom, uz stručno vođenje koje približava istoriju antičke Grčke. Nakon obilaska, predviđena je šetnja kroz Plaku – staru četvrt Atine, sa slobodnim vremenom za uživanje u lokalnim tavernama. Ulaznice uračunate u cenu.',
        duration: 1,
        category: 'Istorija',
        price: 5000,
        maxGroupSize: 20,
        available: true,
        rating: 4,
        numReviews: 22,
    },
    {
        _id: '14',
        name: 'Santorini',
        country: 'Grčka',
        location: 'Santorini, Grčka',
        image: 'https://cdn.sanity.io/images/nxpteyfv/goguides/9ca4581e7f31535984243dfa9c08c12c8a30ffeb-1600x1066.jpg',
        description: 'Program obuhvata obilazak glavnog grada Fire, šetnju kroz bele ulice i posetu lokalnim muzejima. Drugi deo dana je predviđen za vožnju brodom oko vulkanskog ostrva, posetu toplim izvorima i slobodno vreme za degustaciju lokalnih vina. Ulaznice uračunate u cenu.',
        duration: 1,
        category: 'Romantika',
        price: 8000,
        maxGroupSize: 30,
        available: true,
        rating: 5,
        numReviews: 40,
    },
    {
        _id: '15',
        name: 'Meteora — manastiri',
        country: 'Grčka',
        location: 'Meteora, Grčka',
        image: 'https://idsb.tmgrup.com.tr/ly/uploads/images/2024/01/16/310379.jpg',
        description: 'Organizovan obilazak čuvenih manastira Meteora, smeštenih na impresivnim stenama koje dominiraju pejzažom Tesalije. Program obuhvata posetu nekoliko aktivnih manastira, uz stručno vođenje koje približava istoriju, arhitekturu i duhovni značaj ovog jedinstvenog kompleksa. Tokom dana predviđena je šetnja vidikovcima sa panoramskim pogledom na dolinu i slobodno vreme za uživanje u lokalnoj atmosferi. Izlet je osmišljen da spoji kulturno-istorijsko nasleđe, prirodne lepote i duhovni mir Meteora',
        duration: 1,
        category: 'Kultura',
        price: 3000,
        maxGroupSize: 15,
        available: true,
        rating: 4,
        numReviews: 15,
    },
    {
        _id: '16',
        name: 'Izlet na Krf',
        country: 'Grčka',
        location: 'Krf, Grčka',
        image: 'https://www.ponte.rs/UPLOADS-PONTE/2023/02/KRF-OSTRVO.jpg',
        description: 'Izlet obuhvata obilazak glavnog grada ostrva – Krf (Kerkyra), sa šetnjom kroz staru tvrđavu, Liston promenadu i posetu crkvi Svetog Spiridona. Zatim program uključuje posetu Achilleion palati, letnjoj rezidenciji carice Elizabete, kao i obilazak Kanoni vidikovca sa pogledom na ostrvce Pontikonisi. Predviđeno je i slobodno vreme na jednoj od plaža ostrva. Ulaznice uključene u cenu.',
        duration: 1,
        category: 'Priroda',
        price: 7000,
        maxGroupSize: 20,
        available: true,
        rating: 4.5,
        numReviews: 18,
    },
];

export default tours;